disable set-pipeline-exit-status

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -123,41 +123,41 @@ jobs:
 #          tag: "v${{ inputs.version }}"
 #          message: "Version ${{ inputs.version }}"
 #
-  set-pipeline-exit-status:
-    # This step is just so we can make github require this step, to pass checks
-    # on a pull request instead of requiring all
-    name: Set the CI Pipeline Exit Status
-    runs-on: ubuntu-latest
-    if: always()
-    needs:
-      - pre-commit
-      - test
-      - docs
-#      - build-python-package
-#      - deploy-python-package-test-pypi
-#      - deploy-python-package
-#      - push-tag
-    steps:
-    - name: Download Exit Status Files
-      if: always()
-      uses: actions/download-artifact@v3
-      with:
-        name: exitstatus
-        path: exitstatus
-
-    - name: Delete Exit Status Artifacts
-      if: always()
-      uses: geekyeggo/delete-artifact@v2
-      with:
-        name: exitstatus
-        failOnError: false
-
-    - name: Set Pipeline Exit Status
-      run: |
-        tree exitstatus
-        grep -RE 'failure|cancelled' exitstatus/ && exit 1 || exit 0
-
-    - name: Done
-      if: always()
-      run:
-        echo "All workflows finished"
+#  set-pipeline-exit-status:
+#    # This step is just so we can make github require this step, to pass checks
+#    # on a pull request instead of requiring all
+#    name: Set the CI Pipeline Exit Status
+#    runs-on: ubuntu-latest
+#    if: always()
+#    needs:
+#      - pre-commit
+#      - test
+#      - docs
+##      - build-python-package
+##      - deploy-python-package-test-pypi
+##      - deploy-python-package
+##      - push-tag
+#    steps:
+#    - name: Download Exit Status Files
+#      if: always()
+#      uses: actions/download-artifact@v3
+#      with:
+#        name: exitstatus
+#        path: exitstatus
+#
+#    - name: Delete Exit Status Artifacts
+#      if: always()
+#      uses: geekyeggo/delete-artifact@v2
+#      with:
+#        name: exitstatus
+#        failOnError: false
+#
+#    - name: Set Pipeline Exit Status
+#      run: |
+#        tree exitstatus
+#        grep -RE 'failure|cancelled' exitstatus/ && exit 1 || exit 0
+#
+#    - name: Done
+#      if: always()
+#      run:
+#        echo "All workflows finished"
